/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix.jar.app;

import matrix.lib.Matrix;

public class App {
    public static void main(String[] args) {
        int size = 0, module = 0;
        boolean print = false;
        try {
            size = Integer.parseInt(args[0]);
            module = Integer.parseInt(args[1]);
            print = Boolean.parseBoolean(args[2]);
        } catch (Exception ex) {
            System.out.println("Something is wrong with your arguments");
        }

        Matrix matrix_a = new Matrix(size);
        matrix_a.fill(module);
        Matrix matrix_b = new Matrix(size);
        matrix_b.fill(module);
        Matrix matrix_computed = matrix_a.multiply(matrix_b);

        if (print) {
            System.out.println("Matrix A");
            System.out.println(matrix_a);
            System.out.println("Matrix B");
            System.out.println(matrix_b);
            System.out.println("Computed matrix");
            System.out.println(matrix_computed);
        }
    }
}
