/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix.jar.app;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Ignore
    @Test public void testApp() {
        App classUnderTest = new App();
        assertTrue(true);
    }
}
